version: "3.8"

name: passtrack

services:
  postgres-db:
    container_name: passtrack_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: yin
      POSTGRES_PASSWORD: yang
      POSTGRES_DB: passtrack_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5425:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
    driver: local

